### ISSUE TITLE
TypeError: 'MemoryError' object is not iterable

### ISSUE THREAD

**Issue by igvog** [Mphasis-ML-Marketplace/Product-Recommender-for-Retail#1]
Computing the msd similarity matrix...
/usr/local/lib/python3.6/dist-packages/werkzeug/filesystem.py:60: BrokenFilesystemWarning: Detected a misconfigured UNIX filesystem: Will use UTF-8 as filesystem encoding instead of 'ascii'
  BrokenFilesystemWarning,
Debugging middleware caught exception in streamed response at a point where response headers were already sent.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/wsgi.py", line 506, in __next__
    return self._next()
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/wrappers/base_response.py", line 45, in _iter_encoded
    for item in iterable:
TypeError: 'MemoryError' object is not iterable
169.254.255.130 - - [04/Oct/2022 11:27:27] "POST /invocations HTTP/1.1" 200 -
Computing the msd similarity matrix...
/usr/local/lib/python3.6/dist-packages/werkzeug/filesystem.py:60: BrokenFilesystemWarning: Detected a misconfigured UNIX filesystem: Will use UTF-8 as filesystem encoding instead of 'ascii'
  BrokenFilesystemWarning,
Debugging middleware caught exception in streamed response at a point where response headers were already sent.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/wsgi.py", line 506, in __next__
    return self._next()
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/wrappers/base_response.py", line 45, in _iter_encoded
    for item in iterable:
TypeError: 'MemoryError' object is not iterable
169.254.255.130 - - [04/Oct/2022 11:27:27] "POST /invocations HTTP/1.1" 200 -
2022-10-04T11:27:23.701:[sagemaker logs]: MaxConcurrentTransforms=1, MaxPayloadInMB=100, BatchStrategy=MULTI_RECORD

**Comment by igvog** [comment]
works only with small files
